exports.OCCUPATION_STATUS = {
    PROFESSOR: "PROFESSOR",
    STUDENT: "STUDENT"
}

exports.AVAILABILITY = {
    AVAILABLE: "AVAILABLE",
    NOT_AVAILABLE: "NOT_AVAILABLE"
}

exports.ACTIVE = {
    ACTIVE: "ACTIVE",
    NOT_ACTIVE: "NOT_ACTIVE"
}