const ERROR_TOKEN_MISSING = "ERROR_TOKEN_MISSING";
const ERROR_INVALID_TOKEN = "ERROR_INVALID_TOKEN";
const ERROR_INTERNAL_SERVER_ERROR = "ERROR_INTERNAL_SERVER_ERROR";
const ERROR_INVALID_FIELD = "ERROR_INVALID_FIELD";
const ERROR_FIELDS_MISSING = "ERROR_FIELDS_MISSING";
const ERROR_EMAIL_ALREADY_IN_USE = "ERROR_EMAIL_ALREADY_EXISTS";
const ERROR_INVALID_EMAIL = "ERROR_INVALID_EMAIL";
const ERROR_INVALID_NAME = "ERROR_INVALID_NAME";
const ERROR_INVALID_PASSWORD = "ERROR_INVALID_PASSWORD";
const ERROR_INVALID_LASTNAME = "ERROR_INVALID_LASTNAME";
const ERROR_FIELDS_EMAIL_MALFORMED_OR_MISSING =
  "ERROR_FIELDS_EMAIL_MALFORMED_OR_MISSING";
const ERROR_FIELDS_PASSWORD_MALFORMED_OR_MISSING =
  "ERROR_FIELDS_PASSWORD_MALFORMED_OR_MISSING";
const ERROR_INVALID_EMAIL_OR_PASSWORD = "ERROR_INVALID_EMAIL_OR_PASSWORD";
const ERROR_OCCUPATION_INVALID = "ERROR_OCCUPATION_INVALID"
const ERROR_NO_SUCH_USER_FOUND = "ERROR_NO_SUCH_USER_FOUND";
const ERROR_INVALID_START_DATE = "ERROR_INVALID_START_DATE";
const ERROR_INVALID_STOP_DATE = "ERROR_INVALID_STOP_DATE";
const ERROR_MISSING_ITEM_NAME = "ERROR_MISSING_ITEM_NAME"
const ERROR_MISSING_TIMES_FIELD = "ERROR_MISSING_TIMES_FIELD"
const ERROR_MISSING_TIME_INFORMATION = "ERROR_MISSING_TIME_INFORMATION"
const ERROR_DAY_FIELD_ERROR = "ERROR_DAY_FIELD_ERROR"
const ERROR_MONTH_FIELD_ERROR = "ERROR_MONTH_FIELD_ERROR"
const ERROR_YEAR_FIELD_ERROR = "ERROR_YEAR_FIELD_ERROR"
const ERROR_WEEKDAY_FIELD_ERROR = "ERROR_WEEKDAY_FIELD_ERROR"
const ERROR_INVALID_START_TIME = "ERROR_INVALID_START_TIME"
const ERROR_INVALID_END_TIME = "ERROR_INVALID_END_TIME"
const ERROR_MISSING_FIELD_AVAILABILITY = "ERROR_MISSING_FIELD_AVAILABILITY"
const ERROR_MISSING_FIELD_RECURRING = "ERROR_MISSING_FIELD_RECURRING"
const ERROR_MISSING_FIELD_ITEM_ID = "ERROR_FIELD_MISSING_ITEM_ID"
const ERROR_ITEM_NOT_FOUND = "ERROR_ITEM_NOT_FOUND"
const ERROR_ITEM_CANNOT_BE_DELETED = "ERROR_ITEM_CANNOT_BE_DELETED"
const ERROR_INVALID_PROFESSOR_ITEM_ID = "ERROR_INVALID_PROFESSOR_ITEM_ID"
const ERROR_COULD_NOT_ADD_TIME_ITEM = "ERROR_COULD_NOT_ADD_TIME_ITEM"
const ERROR_MISSING_FIELD_ITEM_PARENT_ID = "ERROR_MISSING_FIELD_ITEM_PARENT_ID"
const ERROR_INVALID_TIME_FRAME = "ERROR_INVALID_TIME_FRAME"
const ERROR_INVALID_FIELD_DESCRIPTION = "ERROR_INVALID_FIELD_DESCRIPTION"

exports.ERRORS = {
  ERROR_TOKEN_MISSING,
  ERROR_INVALID_TOKEN,
  ERROR_INTERNAL_SERVER_ERROR,
  ERROR_INVALID_FIELD,
  ERROR_EMAIL_ALREADY_IN_USE,
  ERROR_FIELDS_EMAIL_MALFORMED_OR_MISSING,
  ERROR_FIELDS_PASSWORD_MALFORMED_OR_MISSING,
  ERROR_INVALID_EMAIL_OR_PASSWORD,
  ERROR_NO_SUCH_USER_FOUND,
  ERROR_INVALID_EMAIL,
  ERROR_INVALID_NAME,
  ERROR_INVALID_PASSWORD,
  ERROR_INVALID_LASTNAME,
  ERROR_FIELDS_MISSING,
  ERROR_INVALID_START_DATE,
  ERROR_INVALID_STOP_DATE,
  ERROR_OCCUPATION_INVALID,
  ERROR_MISSING_ITEM_NAME,
  ERROR_MISSING_TIME_INFORMATION,
  ERROR_MISSING_TIMES_FIELD,
  ERROR_DAY_FIELD_ERROR,
  ERROR_MONTH_FIELD_ERROR,
  ERROR_YEAR_FIELD_ERROR,
  ERROR_WEEKDAY_FIELD_ERROR,
  ERROR_INVALID_START_TIME,
  ERROR_INVALID_END_TIME,
  ERROR_MISSING_FIELD_AVAILABILITY,
  ERROR_MISSING_FIELD_RECURRING,
  ERROR_ITEM_NOT_FOUND,
  ERROR_ITEM_CANNOT_BE_DELETED,
  ERROR_INVALID_PROFESSOR_ITEM_ID,
  ERROR_INVALID_TIME_FRAME,
  ERROR_COULD_NOT_ADD_TIME_ITEM,
  ERROR_MISSING_FIELD_ITEM_ID,
  ERROR_MISSING_FIELD_ITEM_PARENT_ID,
  ERROR_INVALID_FIELD_DESCRIPTION
};
